version: '3.9'

services:
  django-web:
    build: .
    container_name: django-casuite
    restart: always
    command: /entrypoint.sh
    ports:
      - "8092:8000"
    env_file:
      - .env
    volumes:
      - /home/data/casuite/static:/app/staticfiles
      - /home/data/casuite/media:/app/media/
      # PERSISTENT MIGRATIONS VOLUME
      - django_migrations_casuite:/app/home/migrations
    # Database is now external, so we remove depends_on
    networks:
      - casuite-network

volumes:
  django_migrations_casuite:

networks:
  casuite-network:
    driver: bridge